run:
  modules-download-mode: readonly
  tests: true
output:
  path-prefix: ""
linters:
  enable:
    - dupl
    - errcheck
    - errname
    - errorlint
    - gocritic
    - gocyclo
    - godot
    - govet
    - ineffassign
    - misspell
    - nlreturn
    - noctx
    - prealloc
    - revive
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - wsl
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
        path: _test\.go
      - linters:
          - govet
        text: 'copylocks:'
      - path: (.+)\.go$
        text: EXC0012
      - path: (.+)\.go$
        text: EXC0013
      - path: (.+)\.go$
        text: EXC0014
      - path: (.+)\.go$
        text: EXC0015
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  new: false
